# .streamlit/secrets.toml
# Este archivo NO debe subirse a GitHub (está en .gitignore)
# Úsalo localmente O configura los secrets en Streamlit Cloud

GEMINI_API_KEY = "AIzaSy-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
